Fixing issue where the "Reset Password" feature sends six-digit codes to any email address that a user has entered in the first page of the "Reset Password" feature instead of his or her most recent email address and fixing the issue where a NoSuchMethodError exception occurs when a user enters in a username that does not exist in the first page of the "Reset Password" feature